version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "5005:80"
    volumes:
      - ./apiGateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-service
      - book-service
      - admin-service
      - frontend
    networks:
      - app-network

  auth-service:
    image: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
    ports:
      - "5003:5003"
    networks:
      - app-network

  user-service:
    image: ${{ secrets.DOCKER_USERNAME }}/user-service:latest
    ports:
      - "5004:5004"
    networks:
      - app-network

  book-service:
    image: ${{ secrets.DOCKER_USERNAME }}/book-service:latest
    ports:
      - "5002:5002"
    networks:
      - app-network

  admin-service:
    image: ${{ secrets.DOCKER_USERNAME }}/admin-service:latest
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
