version: "3.8"

services:
  auth-service:
    image: "${DOCKER_USERNAME}/auth-service:latest"
    ports:
      - "5003:5003"
    networks:
      - app-network

  user-service:
    image: "${DOCKER_USERNAME}/user-service:latest"
    ports:
      - "5004:5004"
    networks:
      - app-network

  book-service:
    image: "${DOCKER_USERNAME}/book-service:latest"
    ports:
      - "5002:5002"
    networks:
      - app-network

  admin-service:
    image: "${DOCKER_USERNAME}/admin-service:latest"
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    image: "${DOCKER_USERNAME}/frontend:latest"
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
