name: Deploy Library Management System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Admin Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/admin-service:latest ./adminService
          docker push ${{ secrets.DOCKER_USERNAME }}/admin-service:latest

      - name: Build and Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./authService
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and Push User Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./userService
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and Push Book Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/book-service:latest ./bookService
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest

      - name: Build and Push Frontend Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --remove-orphans
